export const enum authActionTypes {
	SEND_AUTH_DATA = '@@AUTH/SEND_AUTH_DATA',
	START_AUTH_REQUEST = '@@AUTH/START_AUTH_REQUEST',
	STOP_AUTH_REQUEST = '@@AUTH/STOP_AUTH_REQUEST',
	REFRESH_TOKEN = '@@AUTH/REFRESH_TOKEN',
	START_TOKEN_REFRESH = '@@AUTH/START_TOKEN_REFRESH',
	STOP_TOKEN_REFRESH = '@@AUTH/STOP_TOKEN_REFRESH',
	LOGIN = '@@AUTH/LOGIN',
	LOGOUT = '@@AUTH/LOGOUT',
	VERIFY_TOKEN = '@@AUTH/VERIFY_TOKEN',
}
