export const CANCEL: any;
export const END: any;
export const buffers: any;
export const channel: any;
export default function _default(...args: any[]): any;
export const delay: any;
export const detach: any;
export const effects: {
	actionChannel: any;
	all: any;
	apply: any;
	call: any;
	cancel: any;
	cancelled: any;
	cps: any;
	flush: any;
	fork: any;
	getContext: any;
	join: any;
	put: any;
	race: any;
	select: any;
	setContext: any;
	spawn: any;
	take: any;
	takeEvery: any;
	takeLatest: any;
	takem: any;
	throttle: any;
};
export const eventChannel: any;
export const runSaga: any;
export const takeEvery: any;
export const takeLatest: any;
export const throttle: any;
export const utils: {
	CHANNEL_END: any;
	SAGA_ACTION: any;
	TASK: any;
	arrayOfDeffered: any;
	asEffect: any;
	cloneableGenerator: any;
	createMockTask: any;
	deferred: any;
	is: any;
	noop: any;
};
